# Autogenerated wrapper script for WhiteboxTools_jll for armv7l-linux-gnueabihf
export conditional_evaluation, edge_contamination, exposure_towards_wind_flux, qin_flow_accumulation, quinn_flow_accumulation, raster_calculator, rho8_flow_accumulation, split_vector_lines, whitebox_tools

JLLWrappers.@generate_wrapper_header("WhiteboxTools")
JLLWrappers.@declare_executable_product(conditional_evaluation)
JLLWrappers.@declare_executable_product(edge_contamination)
JLLWrappers.@declare_executable_product(exposure_towards_wind_flux)
JLLWrappers.@declare_executable_product(qin_flow_accumulation)
JLLWrappers.@declare_executable_product(quinn_flow_accumulation)
JLLWrappers.@declare_executable_product(raster_calculator)
JLLWrappers.@declare_executable_product(rho8_flow_accumulation)
JLLWrappers.@declare_executable_product(split_vector_lines)
JLLWrappers.@declare_executable_product(whitebox_tools)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        conditional_evaluation,
        "bin/conditional_evaluation",
    )

    JLLWrappers.@init_executable_product(
        edge_contamination,
        "bin/edge_contamination",
    )

    JLLWrappers.@init_executable_product(
        exposure_towards_wind_flux,
        "bin/exposure_towards_wind_flux",
    )

    JLLWrappers.@init_executable_product(
        qin_flow_accumulation,
        "bin/qin_flow_accumulation",
    )

    JLLWrappers.@init_executable_product(
        quinn_flow_accumulation,
        "bin/quinn_flow_accumulation",
    )

    JLLWrappers.@init_executable_product(
        raster_calculator,
        "bin/raster_calculator",
    )

    JLLWrappers.@init_executable_product(
        rho8_flow_accumulation,
        "bin/rho8_flow_accumulation",
    )

    JLLWrappers.@init_executable_product(
        split_vector_lines,
        "bin/split_vector_lines",
    )

    JLLWrappers.@init_executable_product(
        whitebox_tools,
        "bin/whitebox_tools",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
